### ISSUE TITLE
recommended changes

### ISSUE THREAD

**Issue by Bergiu** [purofle/vim-mindustry-logic#4]
there are some parts i would like to change:
- special highlighting for @variables like: @counter, @thisx, @thisy
- highlight TODO, XXX, FIXME and NOTE
- maybe highlight subinstructions too (i'm not sure about this)

maybe you like these ideas. i will make a pr for them.

**Comment by purofle** [comment]
Waiting for your PR.

**Comment by Bergiu** [comment]
should i include all of them?

**Comment by purofle** [comment]
> should i include all of them?

yes if you want to.
